application: jingblogost
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /templete/css
  static_dir: templete/css
- url: /templete/fonts
  static_dir: templete/fonts
- url: /templete/js
  static_dir: templete/js
- url: /addblog  
  script: main.app
  login: required
  secure: always
- url: /manageblog  
  script: main.app
  login: required
  secure: always
- url: /editblog  
  script: main.app
  login: required
  secure: always
- url: /deleteblog  
  script: main.app
  login: required
  secure: always
- url: /addpost  
  script: main.app
  login: required
  secure: always
- url: /editpost  
  script: main.app
  login: required
  secure: always  
- url: /savepost  
  script: main.app
  login: required
  secure: always    
- url: /deletepost  
  script: main.app
  login: required
  secure: always  
- url: /managepost
  script: main.app
  login: required
  secure: always  
- url: /uploadphoto  
  script: main.app
  login: required
  secure: always  
- url: /managephoto
  script: main.app
  login: required
  secure: always    
- url: /deletephoto
  script: main.app
  login: required
  secure: always     
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"

- name: jinja2
  version: latest